// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package store

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (title, body) VALUES ($1, $2) RETURNING id, title, body
`

type CreatePostParams struct {
	Title *string
	Body  *string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.Title, arg.Body)
	var i Post
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM post WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, body FROM post WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, body FROM post ORDER BY id
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(&i.ID, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE post SET title = $2, body = $3 WHERE id = $1 RETURNING id, title, body
`

type UpdatePostParams struct {
	ID    int32
	Title *string
	Body  *string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Title, arg.Body)
	var i Post
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}
